"""Initial migration.

Revision ID: 41cfc135c4e5
Revises: 
Create Date: 2025-02-04 01:36:02.239037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cfc135c4e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=100), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('batch_code', sa.String(length=6), nullable=False),
    sa.Column('photo_id', sa.String(length=100), nullable=False),
    sa.Column('completion_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consent')
    op.drop_table('response')
    # ### end Alembic commands ###
