"""Add image_displayed column to Response

Revision ID: 7d2df70c1887
Revises: 86f88461d4d9
Create Date: 2025-02-04 21:37:19.150307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d2df70c1887"
down_revision = "86f88461d4d9"
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('response', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('image_displayed', sa.Boolean(), nullable=False))


def upgrade():
    with op.batch_alter_table("response", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "image_displayed",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("response", schema=None) as batch_op:
        batch_op.drop_column("image_displayed")

    # ### end Alembic commands ###
