"""Add new model for feedback

Revision ID: 86f88461d4d9
Revises: f80bd2d97f30
Create Date: 2025-02-04 20:11:13.526999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f88461d4d9'
down_revision = 'f80bd2d97f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=100), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('features_considered', sa.Text(), nullable=False),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_response')
    # ### end Alembic commands ###
