"""Add mturk_id to Response model

Revision ID: f80bd2d97f30
Revises: 41cfc135c4e5
Create Date: 2025-02-04 19:36:31.317158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80bd2d97f30'
down_revision = '41cfc135c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mturk_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('mturk_id')

    # ### end Alembic commands ###
